### ISSUE TITLE
Warning when compiling VueJS app

### ISSUE THREAD

**Issue by djcaesar9114** [socketio/socket.io-parser#101]
When running `npm run serve` I get this warning:

`54% building 372/407 modules 35 active /home/cesar/projects/node/myproject/client/node_modules/socket.io-parser/dist/binary.js[@vue/compiler-sfc] the >>> and /deep/ combinators have been deprecated. Use :deep() instead`

I have version 3.1.0

**Comment by darrachequesne** [comment]
Hi! That's weird, I am not able to reproduce with the project here: https://github.com/socketio/socket.io/tree/master/examples/private-messaging

(and there is no `>>>` nor `/deep/` in the `socket.io-parser` package)
