### ISSUE TITLE
Invalid Payload

### ISSUE THREAD

**Issue by adeelarshad83** [socketio/socket.io-parser#110]
I am facing invalid payload issue which disconnects the socket session.

I am sending same data on socket after every second via c# application but it breaks after some time with invalid payload issue

kindly guide me on this

I am using socket.io v 4.2.0
socket.io-parser v 4.0.4

My Data
string pgnData = "{\"metadata\":[{\"_ts\":0,\"PGN\":126992,\"PGN_Name\":\"System Time\",\"data\":[{\"PropName\":\"Date\",\"PropValue\":\"NA\",\"Unit\":null},{\"PropName\":\"Time\",\"PropValue\":\"NA\",\"Unit\":null}],\"PropName\":\"Date\",\"PropValue\":\"NA\",\"Unit\":null,\"DroneData\":{\"DroneId\":\"11\",\"Location\":\"Amsterdam\"}},{\"_ts\":0,\"PGN\":129540,\"PGN_Name\":\"GNSS Sats in View\",\"data\":[{\"PropName\":\"Mode\",\"PropValue\":\"Range residuals were calculated after the position\",\"Unit\":\"\"},{\"PropName\":\"Number Of SVs\",\"PropValue\":\"0\",\"Unit\":\"\"}],\"PropName\":\"Number Of SVs\",\"PropValue\":\"0\",\"Unit\":\"\",\"DroneData\":{\"DroneId\":\"11\",\"Location\":\"Amsterdam\"}},{\"_ts\":0,\"PGN\":127257,\"PGN_Name\":\"Attitude\",\"data\":[{\"PropName\":\"Yaw\",\"PropValue\":\"NA\",\"Unit\":\"rad\"},{\"PropName\":\"Pitch\",\"PropValue\":\"NA\",\"Unit\":\"rad\"},{\"PropName\":\"Roll\",\"PropValue\":\"NA\",\"Unit\":\"rad\"}],\"PropName\":\"Yaw\",\"PropValue\":\"NA\",\"Unit\":\"rad\",\"DroneData\":{\"DroneId\":\"11\",\"Location\":\"Amsterdam\"}},{\"_ts\":0,\"PGN\":127251,\"PGN_Name\":\"Rate Of Turn\",\"data\":[{\"PropName\":\"Rate Of Turn\",\"PropValue\":\"NA\",\"Unit\":\"rad/s\"}],\"PropName\":\"Rate Of Turn\",\"PropValue\":\"NA\",\"Unit\":\"rad/s\",\"DroneData\":{\"DroneId\":\"11\",\"Location\":\"Amsterdam\"}},{\"_ts\":0,\"PGN\":127250,\"PGN_Name\":\"Vessel Heading\",\"data\":[{\"PropName\":\"Heading Sensor Reading\",\"PropValue\":\"1.3603\",\"Unit\":\"rad\"}],\"PropName\":\"Heading Sensor Reading\",\"PropValue\":\"1.3603\",\"Unit\":\"rad\",\"DroneData\":{\"DroneId\":\"11\",\"Location\":\"Amsterdam\"}},{\"_ts\":0,\"PGN\":128267,\"PGN_Name\":\"Water Depth\",\"data\":[{\"PropName\":\"Water Depth, Transducer\",\"PropValue\":\"NA\",\"Unit\":\"m\"}],\"PropName\":\"Water Depth, Transducer\",\"PropValue\":\"NA\",\"Unit\":\"m\",\"DroneData\":{\"DroneId\":\"11\",\"Location\":\"Amsterdam\"}},{\"_ts\":0,\"PGN\":129025,\"PGN_Name\":\"Position, Rapid Update\",\"data\":[{\"PropName\":\"Latitude\",\"PropValue\":\"NA\",\"Unit\":\"\"},{\"PropName\":\"Longitude\",\"PropValue\":\"NA\",\"Unit\":\"\"}],\"PropName\":\"Longitude\",\"PropValue\":\"NA\",\"Unit\":\"\",\"DroneData\":{\"DroneId\":\"11\",\"Location\":\"Amsterdam\"}},{\"_ts\":0,\"PGN\":129028,\"PGN_Name\":\"Altitude Delta, High Precision Rapid Update\",\"data\":[{\"PropName\":\"GNSS Quality\",\"PropValue\":\"No GPS\",\"Unit\":\"\"}],\"PropName\":\"GNSS Quality\",\"PropValue\":\"No GPS\",\"Unit\":\"\",\"DroneData\":{\"DroneId\":\"11\",\"Location\":\"Amsterdam\"}},{\"_ts\":0,\"PGN\":128259,\"PGN_Name\":\"Speed Water Referenced\",\"data\":[{\"PropName\":\"Speed Water Referenced\",\"PropValue\":\"0\",\"Unit\":\"m/s\"},{\"PropName\":\"Speed Direction\",\"PropValue\":\"NA\",\"Unit\":null}],\"PropName\":\"Speed Water Referenced\",\"PropValue\":\"0\",\"Unit\":\"m/s\",\"DroneData\":{\"DroneId\":\"11\",\"Location\":\"Amsterdam\"}},{\"_ts\":0,\"PGN\":129026,\"PGN_Name\":\"COG & SOG, Rapid Update\",\"data\":[{\"PropName\":\"Course Over Ground\",\"PropValue\":\"NA\",\"Unit\":\"rad\"},{\"PropName\":\"Speed Over Ground\",\"PropValue\":\"NA\",\"Unit\":\"m/s\"}],\"PropName\":\"Course Over Ground\",\"PropValue\":\"NA\",\"Unit\":\"rad\",\"DroneData\":{\"DroneId\":\"11\",\"Location\":\"Amsterdam\"}},{\"_ts\":0,\"PGN\":130311,\"PGN_Name\":\"Environmental Parameters\",\"data\":[{\"PropName\":\"Temperature\",\"PropValue\":\"20.7\",\"Unit\":\"°C\"},{\"PropName\":\"Humidity\",\"PropValue\":\"NA\",\"Unit\":\"%\"},{\"PropName\":\"Atmospheric Pressure\",\"PropValue\":\"NA\",\"Unit\":\"Pa\"}],\"PropName\":\"Temperature\",\"PropValue\":\"20.7\",\"Unit\":\"°C\",\"DroneData\":{\"DroneId\":\"11\",\"Location\":\"Amsterdam\"}},{\"_ts\":0,\"PGN\":128275,\"PGN_Name\":\"Distance Log\",\"data\":[{\"PropName\":\"Distance Since Last Reset\",\"PropValue\":\"978131\",\"Unit\":\"m\"},{\"PropName\":\"Total Cumulative Distance\",\"PropValue\":\"978131\",\"Unit\":\"m\"}],\"PropName\":\"Distance Since Last Reset\",\"PropValue\":\"978131\",\"Unit\":\"m\",\"DroneData\":{\"DroneId\":\"11\",\"Location\":\"Amsterdam\"}},{\"_ts\":0,\"PGN\":1275080,\"PGN_Name\":\"Battery Status 0\",\"data\":[{\"PropName\":\"Battery Current\",\"PropValue\":\"10.6\",\"Unit\":\"A\"},{\"PropName\":\"Battery Voltage\",\"PropValue\":\"54.92\",\"Unit\":\"V\"},{\"PropName\":\"Battery Case Temperature\",\"PropValue\":\"25\",\"Unit\":\"°C\"}],\"PropName\":\"Battery Current\",\"PropValue\":\"10.6\",\"Unit\":\"A\",\"DroneData\":{\"DroneId\":\"11\",\"Location\":\"Amsterdam\"}},{\"_ts\":0,\"PGN\":1275081,\"PGN_Name\":\"Battery Status 1\",\"data\":[{\"PropName\":\"Battery Current\",\"PropValue\":\"NA\",\"Unit\":\"A\"},{\"PropName\":\"Battery Voltage\",\"PropValue\":\"3.88\",\"Unit\":\"V\"},{\"PropName\":\"Battery Case Temperature\",\"PropValue\":\"21\",\"Unit\":\"°C\"}],\"PropName\":\"Battery Current\",\"PropValue\":\"NA\",\"Unit\":\"A\",\"DroneData\":{\"DroneId\":\"11\",\"Location\":\"Amsterdam\"}},{\"_ts\":0,\"PGN\":1275082,\"PGN_Name\":\"Battery Status 2\",\"data\":[{\"PropName\":\"Battery Current\",\"PropValue\":\"NA\",\"Unit\":\"A\"},{\"PropName\":\"Battery Voltage\",\"PropValue\":\"3.93\",\"Unit\":\"V\"},{\"PropName\":\"Battery Case Temperature\",\"PropValue\":\"25\",\"Unit\":\"°C\"}],\"PropName\":\"Battery Current\",\"PropValue\":\"NA\",\"Unit\":\"A\",\"DroneData\":{\"DroneId\":\"11\",\"Location\":\"Amsterdam\"}},{\"_ts\":0,\"PGN\":127506,\"PGN_Name\":\"DC Detailed Status\",\"data\":[{\"PropName\":\"State Of Charge\",\"PropValue\":\"82\",\"Unit\":\"%\"},{\"PropName\":\"State Of Health\",\"PropValue\":\"NA\",\"Unit\":\"%\"},{\"PropName\":\"Time Remaining\",\"PropValue\":\"11641\",\"Unit\":\"min\"},{\"PropName\":\"Amp Hours\",\"PropValue\":\"190800\",\"Unit\":\"C\"}],\"PropName\":\"State Of Charge\",\"PropValue\":\"82\",\"Unit\":\"%\",\"DroneData\":{\"DroneId\":\"11\",\"Location\":\"Amsterdam\"}},{\"_ts\":0,\"PGN\":129029,\"PGN_Name\":\"GNSS Position Data\",\"data\":[{\"PropName\":\"Method, GNSS\",\"PropValue\":\"No GPS\",\"Unit\":\"\"},{\"PropName\":\"Number Of Reference Stations\",\"PropValue\":\"0\",\"Unit\":\"\"}],\"PropName\":\"Method, GNSS\",\"PropValue\":\"No GPS\",\"Unit\":\"\",\"DroneData\":{\"DroneId\":\"11\",\"Location\":\"Amsterdam\"}}],\"type\":\"pgn-data\",\"vesselId\":11,\"surveyId\":0,\"token\":\"/zSReOFi5NW5Vq34BDICHGIPyTHj9MrwIsO2NB8gE0wkX5kXyA\"}";
ws.EmitAsync(EVENT_WEBSOCKET_COMMUNICATION, pgnData);

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
