### ISSUE TITLE
Decode binary message

### ISSUE THREAD

**Issue by ElModdy** [socketio/socket.io-parser#116]
Hi, I'm debugging a web application that uses socket.io.
It sends binary message and I'd like to decode them.
Here an example:

- Base64: `hKR0eXBlAqRkYXRhkqFtks0CdMtAf48AAAAAAKdvcHRpb25zgahjb21wcmVzc8OjbnNwoS8=`
- UTF-8: `typedatamu@?optionscompressãnsp/`

That's what I've tried:
```node
var parser = require('socket.io-parser');
var decoder = new parser.Decoder();
var b64string = "hKR0eXBlAqRkYXRhkqFtks0CdMtAf48AAAAAAKdvcHRpb25zgahjb21wcmVzc8OjbnNwoS8="
var buf = Buffer.from(b64string, 'base64');
decoder.on('decoded', function(decodedPacket) {
	console.log(decodedPacket)
});

decoder.add(buf);
```

It returns the following error: "Error: got binary data when not reconstructing a packet"

**Comment by ThinhVu** [comment]
![Uploading Screenshot 2023-03-29 at 12.39.34 AM.png…]()

Hmm

**Comment by ThinhVu** [comment]
<img width="1413" alt="Screenshot 2023-03-29 at 12 44 11 AM" src="https://user-images.githubusercontent.com/8122962/228325578-87e834a0-239a-4627-800d-6583ba823224.png">

Damn.

**Comment by darrachequesne** [comment]
The message looks like it was encoded by msgpack, for server-to-server communication. For example, we use it [here](https://github.com/socketio/socket.io-redis-adapter/blob/2d65d0adc7596a5cd305d94b0aaba69bda9260c7/lib/index.ts#L630) in the Redis adapter.

See also: https://github.com/msgpack/msgpack-javascript

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
