### ISSUE TITLE
TypeScript issues

### ISSUE THREAD

**Issue by philkunz** [socketio/socket.io-parser#132]
socket.io-parser@4.2.4/node_modules/socket.io-parser/build/cjs/index.d.ts (1,25): The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@socket.io/component-emitter")' call instead.

**Comment by darrachequesne** [comment]
Hi! I wasn't able to reproduce, could you please provide your `tsconfig.json` config file?

**Comment by philkunz** [comment]
@darrachequesne Sure:

{
    "compilerOptions": {
      "experimentalDecorators": true,
      "useDefineForClassFields": false,
      "target": "ES2022",
      "module": "NodeNext",
      "moduleResolution": "NodeNext",
      "esModuleInterop": true,
      "verbatimModuleSyntax": true
    }
  }

**Comment by plvo** [comment]
hey, same error for me:
```
node_modules/.pnpm/socket.io-parser@4.2.4/node_modules/socket.io-parser/build/cjs/index.d.ts:1:25 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@socket.io/component-emitter")' call instead.

1 import { Emitter } from "@socket.io/component-emitter";
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/.pnpm/socket.io-parser@4.2.4/node_modules/socket.io-parser/build/cjs/index.d.ts:1
```

my `tsconfig.json`:
```json
{
    "compilerOptions": {
        "module": "NodeNext",
        "moduleResolution": "NodeNext",
        "target": "ES2020",
        "sourceMap": true,
        "outDir": "dist",
        "resolveJsonModule": true,
        "esModuleInterop": true,
        "allowArbitraryExtensions": true
    },
    "include": [
        "src/**/*"
    ],
}
```
I use pnpm and build with tsc:
```json
{
  "name": "server",
  "version": "1.0.0",
  "main": "dist/index.js",
  "license": "MIT",
  "type": "module",
  "scripts": {
    "build": "tsc",
    "dev": "node dist/index.js",
    "start": "pnpm build && pnpm dev"
  },
  "dependencies": {
    "cors": "^2.8.5",
    "express": "^4.19.2",
    "socket.io": "^4.7.5"
  },
  "devDependencies": {
    "@types/node": "^20.12.7",
    "typescript": "^5.4.5"
  }
}
```

**Comment by TriangularCube** [comment]
Can confirm, also running into this problem

**Comment by plvo** [comment]
Update: I used `"skipLibCheck": true` on my `tsconfig.json`

source: https://www.typescriptlang.org/tsconfig/#skipLibCheck

**Comment by plvo** [comment]
@philkunz yes it's not the best solution, I use it because it's a small project, but if there are other solutions, I'm interested

**Comment by darrachequesne** [comment]
@philkunz I was indeed able to reproduce the issue, thanks for providing your `tsconfig.json` file :+1: 

This should be fixed by https://github.com/socketio/emitter/commit/e6aa1a331c37697b9de7e91b7db286eac245c8d7, included in `@socket.io/component-emitter@3.1.2`.

Could you please check?

**Comment by philkunz** [comment]
@darrachequesne I comment on the the commit above, but the issue seems fixed for now.

**Comment by philkunz** [comment]
@darrachequesne Thank you!
