### ISSUE TITLE
bg.gif

### ISSUE THREAD

**Issue by timruffles** [socketio/socket.io-parser#26]
there's a giant gif in my node_modules for `2.2.4` :) I can't see it in the repo, else I'd have used `package.json`'s `files` option to cut it out.

**Comment by timruffles** [comment]
![screen shot 2015-03-19 at 12 35 40](https://cloud.githubusercontent.com/assets/249800/6730430/7b88de52-ce34-11e4-9b5f-e48390752b4f.png)

**Comment by jaslo** [comment]
same issue as above! Where does that come from? node-gyp?

**Comment by nkzawa** [comment]
It looks the gif was accidentally published, will be removed in the next release. Thanks for your report!

**Comment by stefanpenner** [comment]
@nkzawa can we got another bump?

**Comment by nkzawa** [comment]
Fixed on 2.2.5
