### ISSUE TITLE
can't parse multiline messages

### ISSUE THREAD

**Issue by cdagli** [socketio/socket.io-parser#29]
Our socket.io configuration works okay when a one line message is received; 

<pre>   
  engine handling "POST" http request "/socket.io/?transport=polling&sid=D4hHosMaFHKF2xZAAAAA" +0ms
  engine setting new request for existing client +1ms!
  engine:polling received "20:42["message","test"]" +0ms
  engine:socket packet +0ms
  socket.io-parser decoded 2["message","test"] as {"type":2,"nsp":"/","data":["message","test"]} +8.2m
  socket.io:socket got packet {"type":2,"nsp":"/","data":["message","test"]} +6m
  socket.io:socket emitting event ["message","test"] +0ms</pre>

But when a multiline message is send it looks like socket.io-parser can't decode the packet; 

<pre>
  engine handling "POST" http request "/socket.io/?transport=polling&sid=D4hHosMaFHKF2xZAAAAA" +0ms
  engine setting new request for existing client +0ms
  engine:polling received "27:42["message","test2
test3"]" +1ms
  engine:socket packet +0ms
  socket.io:client no socket for namespace undefined +1m</pre>

Any thoughts on how can I solve the issue?

Thank you

**Comment by nkzawa** [comment]
As far as I tested, couldn't reproduce the issue. How can we reproduce?

`socket.send('foo\nbar')`

``` 
  engine handling "POST" http request "/socket.io/?EIO=3&transport=polling&t=1432835971871-2&sid=ajyrofMpkOgvBwHAAAAA" +0ms
  engine setting new request for existing client +1ms
  engine:polling received "24:42["message","foo\nbar"]" +2ms
  engine:socket packet +1ms
  socket.io-parser decoded 2["message","foo\nbar"] as {"type":2,"nsp":"/","data":["message","foo\nbar"]} +246ms
  socket.io:socket got packet {"type":2,"nsp":"/","data":["message","foo\nbar"]} +242ms
  socket.io:socket emitting event ["message","foo\nbar"] +0ms
```

**Comment by nkzawa** [comment]
Closed due to inactivity.
