### ISSUE TITLE
errors while install socket.io-parser

### ISSUE THREAD

**Issue by YanhaoMo** [socketio/socket.io-parser#36]
npm install -g socket.io-parser@2.1.2

> npm ERR! fetch failed http://github.com/component/emitter/archive/1.0.1.tar.gz
> npm WARN retry will retry, error on last attempt: Error: read ECONNRESET
> npm ERR! fetch failed http://github.com/component/emitter/archive/1.0.1.tar.gz
> npm WARN retry will retry, error on last attempt: Error: read ECONNRESET

the protocol section of the url should be 'https' , not 'http'

**Comment by nkzawa** [comment]
How can I reproduce ? The error doesn't occur to me.  btw you wouldn't like to install the module globally. It's expected to be used as a library.

**Comment by darrachequesne** [comment]
Closed due to inactivity. Please reopen if needed.
