### ISSUE TITLE
Drop support for old env 

### ISSUE THREAD

**Issue by jimmywarting** [socketio/socket.io-parser#39]
At least drop support for node < 4 and some ie version... i still see ie6 in travis... comon it's dead

**Comment by jamwaffles** [comment]
On top of this, can we drop JSON3 as a dependency too? If it's still required by a significant number of users, can we at least make it an `optionalDependency`? 40KB of pointless polyfill (ok, 10KB gzipped but still...) is quite a burden to put on users.

**Comment by albertogasparin** [comment]
+1 
I'd love to have `json3` removed. People who needs IE6/7 support could provide it by themselves

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/socket.io-parser/pull/64.
