### ISSUE TITLE
Each binary packet results in two packets, and two websocket frames

### ISSUE THREAD

**Issue by darrachequesne** [socketio/socket.io-parser#61]
As described here, currently:

```js
socket.send('hello', new Buffer('1234'));
// results in the following packet
var packet = {
  type: 5,
  data: ['hello', <buffer>],
  nsp: '/',
  // id: <id> (if used with an acknowledgement)
};
// that gets encoded as two packets by socket.io-parser
[
  encodeAsString(packetWithoutBuffer),
  <buffer> 
]
```

The thing is, those two packets are sent as two different frames ([here](https://github.com/socketio/engine.io/blob/1.8.2/lib/transports/websocket.js#L92)), which isn't really efficient (even if a websocket emit does not need a new TCP handshake).

One possible solution would be to concatenate those two packets in one buffer:
```
var stringPacket = encodeAsString(packetWithoutBuffer);
<stringPacket length><stringPacket as buffer><buffer> 
```

Yet that would be a breaking change, and a special case when handling binary data.

Related:
- https://github.com/socketio/socket.io-parser/issues/60: execution time for encodeAsBinary
- https://github.com/socketio/socket.io/issues/2444: Getting three frames instead of two between client/server
- https://github.com/socketio/socket.io/issues/2646: 358 bytes payload takes almost double mobile traffic

**Comment by darrachequesne** [comment]
Closing, since one will now be able use a custom parser, like [socket.io-msgpack-parser](https://github.com/darrachequesne/socket.io-msgpack-parser).

**Comment by nybbs2003** [comment]
👍
