### ISSUE TITLE
.npmignore file

### ISSUE THREAD

**Issue by ORESoftware** [socketio/socket.io-parser#62]
forgive me if I mistaken, but when publishing to NPM looks like node_modules from this project is being included:

```
60      ./socket.io-parser/node_modules/debug
40      ./socket.io-parser/node_modules/component-emitter
28      ./socket.io-parser/node_modules/ms
132     ./socket.io-parser/node_modules
```

the idea would be to add an .npmignore file in this project and add "node_modules" to that file and then publish to NPM, this way you don't include the unnecessary node_modules folder

let me know if maybe I wrong about something thanks!

**Comment by darrachequesne** [comment]
> Additionally, everything in node_modules is ignored, except for bundled dependencies. npm automatically handles this for you, so don't bother adding node_modules to .npmignore.

Reference: https://docs.npmjs.com/misc/developers
