### ISSUE TITLE
isarray package is deprecated: Just use Array.isArray directly

### ISSUE THREAD

**Issue by jharris4** [socketio/socket.io-parser#71]
When installing the latest versions of socket.io, there is a deprecation warning since the isarray package has been deprecated.

Is there any reason to not just use `Array.isArray` ?

**Comment by darrachequesne** [comment]
I think that's because `Array.isArray` is not defined in IE8.

**Comment by jimmywarting** [comment]
it's 2019, do you still support ie8?
