### ISSUE TITLE
Convert type Date to Buffer

### ISSUE THREAD

**Issue by mrbatista** [socketio/socket.io-parser#76]
```js
server:
const data = {created: new Date()};
socket.emit('event', data);

client:
socket.on('event', (data) => {
  console.log(data);
  //print -> "created":{"buffer":{"type":"Buffer","data":[0,0,1,95,72,191,181,7]}
})
```
socket.io@2.0.3
socket.io-client@2.0.3
socket.io-parser@3.1.2

**Comment by gnobre** [comment]
Any updates on this? I don't want my dates converted to buffers, I want them converted to strings

**Comment by gnobre** [comment]
It's converting `undefined` data types to buffer as well

**Comment by gnobre** [comment]
Any updates on this? In my opnion would be better calling the toString method on Dates instead of converting them to buffers. Also, `undefined` types are being converted to empty buffers:

`    "err": {
      "buffer": {
        "type": "Buffer",
        "data": [
          0
        ]
      },
      "type": 0
    }`

**Comment by darrachequesne** [comment]
Hi! I'm not able to reproduce: https://github.com/darrachequesne/socket.io-fiddle/tree/issue/parser-76

```
$ node server.js 
server listening on port 3000
connect IXXRwpfxWTHMymUbAAAB
[ '2018-02-20T11:52:32.632Z', null, null, {} ]

$ node client.js 
connect IXXRwpfxWTHMymUbAAAB
[ '2018-02-20T11:52:32.636Z', null, null, {} ]
```

What is your setup (OS, browser, ...)?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
