### ISSUE TITLE
Message with binary included not decoded; no error thrown no decoded event emitted.

### ISSUE THREAD

**Issue by jeduden** [socketio/socket.io-parser#78]
Creating a message with the socket.io C++ client.
```
auto pMsg = sio::object_message::create();

pMsg->get_map()["a"] = sio::int_message::create(1);
pMsg->get_map()["b"] = sio::int_message::create(2);
std::string bufferAsString(
        (const char *)&(*buffer.begin()),
        (const char *)&(*buffer.end()));
pMsg->get_map()["data"] = sio::binary_message::create(std::make_shared<std::string>(bufferAsString));
    
pSocket->emit("BinaryMsg", pMsg);
```

When this gets parsed by the socket.io parser, the reconstructor object looks like this:
```
socket.io-parser Reconstructor: BinaryReconstructor {
  socket.io-parser   reconPack:
  socket.io-parser    { type: 5,
  socket.io-parser      attachments: 1,
  socket.io-parser      nsp: '/somens/0',
  socket.io-parser      data: [ 'BinaryMsg', [Object] ] },
  socket.io-parser   buffers: [] }
```

https://github.com/socketio/socket.io-parser/blob/master/index.js#L237
```
     // no attachments, labeled binary but no binary data to follow
      if (this.reconstructor.reconPack.attachments === 0) {
        this.emit('decoded', packet);
      }
```
evaluates to false, since there is one attachment.
However, no other part of the `add` function emits `decoded`, hence the packet is dropped. 

is this intended ?

**Comment by darrachequesne** [comment]
For future readers:

This was fixed by https://github.com/socketio/socket.io-parser/commit/b5d0cb7dc56a0601a09b056beaeeb0e43b160050, included in version [4.2.1](https://github.com/socketio/socket.io-parser/releases/tag/4.2.1).
