### ISSUE TITLE
use of global in binary check fails in angular 6 applications

### ISSUE THREAD

**Issue by psylum** [socketio/socket.io-parser#87]
Ideally this package should follow `socketio/socket.io-client` and also depend on `has-binary2` which has been patched for this issue. Otherwise a patch is discussed that may be suitable.

See discussion in socketio/socket.io-client#1166 and socketio/socket.io-client#1206.

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/socket.io-parser/commit/b47efb270d959e7456d8d44b4f3c386a884542b8 (and included in `socket.io-parser>=3.3.0`)
